


export const English = {
    profle_header: 'Profile',
    profile_name: 'Mark Jhonson',
    profile_subscribe: "Subscribe",
    my_Profile: "My Profile",
    settings: 'Settings',
    downloads: 'Downloads',
    privacy_policy: 'Privacy Policy',
    support: 'Support',
    logout: 'Logout',
    light_theme: 'Light Theme',
    dark_theme: 'Dark Theme',
    subscription_header: 'Subscription',
    starter_pack: 'STARTER PACK',
    month: 'Month',
    why_premium: 'Why Upgrade To premium?',
    premium_first: 'Get Access To Full HD Content.',
    premium_second: 'Free Downloading Of Movies & Series',
    premium_third: 'Watch Exclusive Content',
    payment_select: 'Select any method to Pay',
    paypal: 'PayPal',
    googlepay: 'Google Pay',
    phonepay: 'Phone Pay',
    card_type: 'Credit or Debit Card',
    stripe: 'Stripe',
    payment_message: 'Hurray!',
    payment_status: 'Payment Succesfull.',
    subscription_started: 'Your Subscription has Started!',
    back_home: 'Back To Home',
    full_name: 'Full Name',
    email: 'Email Address',
    email_static: 'markjhonson@email.com',
    phone_number: 'Phone Number',
    phone_number_static: '912345678',
    save: 'Save',
    preferred_lang: 'Preferred App Language',
    downlaod_type: 'Download',
    download_quality: 'Download Video Quality',
    privacy_policy_1: '',
    privacy_policy_2: '',
    privacy_policy_3: '',
    connect: 'Connect With Us',
    call_us: 'Call us',
    mail_us: 'Mail us',
    address: 'Address',
    address_line_1: 'ABC Building INC.',
    address_line_2: '123 Corporate Estate',
    address_line_3: 'XYZ Road',
    address_line_1: 'Tokyo - 121321',
    logout_confirmation: 'Are you sure you want to logout ?',
    logout_confirmation_1: 'All your Settings, Download and Wishlist will be Lost!',
    cancel: 'Cancel',
}


// export const lang = [
//     {
//         "title": "English",
//         "data": {
//             profle_header: 'Profile',
//             profile_name: 'Mark Jhonson',
//             profile_subscribe: "Subscribe",
//             my_Profile: "My Profile",
//             settings: 'Settings',
//             downloads: 'Downloads',
//             privacy_policy: 'Privacy Policy',
//             support: 'Support',
//             logout: 'Logout',
//             light_theme: 'Light Theme',
//             dark_theme: 'Dark Theme',
//             subscription_header: 'Subscription',
//             starter_pack: 'STARTER PACK',
//             month: 'Month',
//             why_premium: 'Why Upgrade To premium?',
//             premium_first: 'Get Access To Full HD Content.',
//             premium_second: 'Free Downloading Of Movies & Series',
//             premium_third: 'Watch Exclusive Content',
//             payment_select: 'Select any method to Pay',
//             paypal: 'PayPal',
//             googlepay: 'Google Pay',
//             phonepay: 'Phone Pay',
//             card_type: 'Credit or Debit Card',
//             stripe: 'Stripe',
//             payment_message: 'Hurray!',
//             payment_status: 'Payment Succesfull.',
//             subscription_started: 'Your Subscription has Started!',
//             back_home: 'Back To Home',
//             full_name: 'Full Name',
//             email: 'Email Address',
//             email_static: 'markjhonson@email.com',
//             phone_number: 'Phone Number',
//             phone_number_static: '912345678',
//             save: 'Save',
//             preferred_lang: 'Preferred App Language',
//             downlaod_type: 'Download',
//             download_quality: 'Download Video Quality',
//             privacy_policy_1: '',
//             privacy_policy_2: '',
//             privacy_policy_3: '',
//             connect: 'Connect With Us',
//             call_us: 'Call us',
//             mail_us: 'Mail us',
//             address: 'Address',
//             address_line_1: 'ABC Building INC.',
//             address_line_2: '123 Corporate Estate',
//             address_line_3: 'XYZ Road',
//             address_line_1: 'Tokyo - 121321',
//             logout_confirmation: 'Are you sure you want to logout ?',
//             logout_confirmation_1: 'All your Settings, Download and Wishlist will be Lost!',
//             cancel: 'Cancel',
//         }
//     },
//     {
//         "title": "Hindi",
//         "data": {
//             profle_header: 'प्रोफाइल',
//             profile_name: 'मार्क जॉनसन',
//             profile_subscribe: "सदस्यता लें",
//             my_Profile: "मेरी प्रोफ़ाइल",
//             settings: 'सेटिंग्स',
//             downloads: 'डाउनलोड',
//             privacy_policy: 'गोपनीयता नीति',
//             support: 'समर्थन',
//             logout: 'लॉगआउट',
//             light_theme: 'लाइट थीम',
//             dark_theme: 'डार्क थीम',
//         }
//     }

// ]

